### ISSUE TITLE
Future possibilities? 

### ISSUE THREAD

**Issue by Lariabeth** [hefnerj1/macromorphoscopic#8]
Do you have plans to integrate metrics into the morphoscopic data ? (again, similar to HumanID) - I've run a handful of data through MaMD and compared them to metric analysis results from FORDISC and I'm getting very different ancestry predictions from each

**Comment by hefnerj1** [comment]
No. I think some of the misclassification issues will be corrected as we move from aNN to other classification methods. I also think that there will be some crania that will always classify differently in FD3. I've looked into the cause of this and was able to identify differences in character states (sometimes just a single trait) can shift the classification. So double check your trait scores and if unsure, it is actually better to not use that trait than to include it

**Comment by hefnerj1** [comment]
Can you provide any more info about the cases you had that classified.

**Comment by Lariabeth** [comment]
I take back my previous issue! I've run six cases through MaMD and compared them with other analyses and there is one that is giving me contradictory results - but there is postmortem damage and missing data - so this is expected.  The other five are giving expected results with MaMD so far.  I'll close this and let you know if it comes up in the future!
